name: Build and Deploy chatgptui

environment:
  name: WEBRTC_TEST

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build with Vite
        run: npm run build

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t seasonschange422/webrtctest-front .

      - name: Push Docker image
        run: docker push seasonschange422/webrtctest-front

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ID }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            docker stop CHATWEB || true
            docker rm CHATWEB || true
            docker rmi $(docker images seasonschange422/webrtctest-front -q) || true
            sleep 3
            docker pull https://registry.docker-cn.com/seasonschange422/webrtctest-front
            docker run --name webrtctestFrontContainer -d -p 0.0.0.0:3000:3000 seasonschange422/webrtctest-front
